### ISSUE TITLE
push: investigate lack of --info support on rsync on OSX

### ISSUE THREAD

**Issue by maruel** [periph/bootstrap#5]
If a user install `rsync` via homebrew, this version does support --info.
`push` needs to figure out and only add the flag if supported.

**Comment by yupi** [comment]
--info option first appeared in 3.1.0 version of rsync according to https://download.samba.org/pub/rsync/src/rsync-3.1.0-NEWS

**Comment by maruel** [comment]
My preference is to probe the rsync version, then pass the right flags based on the installer version.

**Comment by maruel** [comment]
Fixed by https://github.com/periph/bootstrap/commit/daabf82d3a0a650ef939c0c1852925afdb5eba4a.
